apiVersion: v1
kind: Pod
metadata:
  name: gpu-application
spec:
  restartPolicy: OnFailure
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/cuda:11.8.0-base-ubuntu22.04
      command: ["bash", "-c", "nvidia-smi && sleep infinity"]
      resources:
        limits:
          nvidia.com/gpu: 1 # Request 1 GPU